extensions:
  - ".py"
  - ".js"
  - ".java"
  - ".go"
  - ".rb"
  - ".php"
  - ".c"
  - ".cpp"
  - ".html"
  - ".sql"
  - ".ts"
  - ".yaml"
  - ".yml"
  - ".json"

ignore_dirs:
  - ".git"
  - "node_modules"
  - "venv"
  - "__pycache__"
  - ".env"
  - "vendor"
  - "tests"
  - "docs"
  - "rules"
